import type { Metadata } from "next";
import "./globals.css";
import HydrationZustand from "@/store/hydrationZustand";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HydrationZustand>{children}</HydrationZustand>
      </body>
    </html>
  );
}
